"""
Mini-catalog loader for matching constraints.

The mini-catalog is a JSON file containing lightweight course metadata including
matching_required and matching_type fields. It's generated by the build script
and committed to the repo for static serving.

Configuration:
- MINICATALOG_PATH env var (default: data/mini_catalog.json, relative to api/)
- If the path contains "{term}", it will be formatted with the term value.
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

# Cache mini-catalogs in memory
_catalog_cache: Dict[str, Dict[str, Any]] = {}


def normalize_code(code: str) -> str:
    """Normalize course code for catalog lookup (e.g., 'comp   2011' -> 'COMP 2011')."""
    cleaned = " ".join(code.strip().upper().split())
    return cleaned


def _resolve_catalog_path(term: str) -> Path:
    """Resolve catalog path from env or default."""
    path_template = os.getenv("MINICATALOG_PATH", "data/mini_catalog.json")
    if "{term}" in path_template:
        path_template = path_template.format(term=term)
    candidate = Path(path_template)
    if candidate.is_absolute():
        return candidate
    return Path(__file__).parent / candidate


def _find_catalog_path(term: str) -> Optional[Path]:
    """Find the mini-catalog file for a term."""
    resolved = _resolve_catalog_path(term)
    if resolved.exists() and resolved.stat().st_size > 0:
        return resolved
    return None


def load_mini_catalog(term: str, force_refresh: bool = False) -> Dict[str, Any]:
    """
    Load the mini-catalog for a term.
    
    Returns a dict mapping course_code -> catalog entry.
    The entry contains: course_code, title, units, subject,
    and optionally: matching_required, matching_type, header_remarks
    
    Raises RuntimeError if catalog not found.
    """
    cache_key = term
    
    if not force_refresh and cache_key in _catalog_cache:
        return _catalog_cache[cache_key]
    
    catalog_path = _find_catalog_path(term)
    if not catalog_path:
        raise RuntimeError(
            f"Mini-catalog not found. Set MINICATALOG_PATH or place file at {str(_resolve_catalog_path(term))}."
        )
    
    try:
        with open(catalog_path, "r") as f:
            entries = json.load(f)
        
        # Build lookup dict by course_code
        catalog = {}
        for entry in entries:
            code = entry.get("course_code")
            if code:
                catalog[normalize_code(code)] = entry
        
        _catalog_cache[cache_key] = catalog
        return catalog
    
    except Exception as e:
        raise RuntimeError(f"Failed to load mini-catalog for {term}: {e}") from e


def get_matching_constraint(term: str, course_code: str) -> tuple[bool, Optional[str]]:
    """
    Get matching constraint for a specific course.
    
    Returns (matching_required, matching_type).
    Returns (False, None) if course not found in catalog.
    """
    catalog = load_mini_catalog(term)
    entry = catalog.get(normalize_code(course_code), {})
    
    return (
        entry.get("matching_required", False),
        entry.get("matching_type")
    )


def clear_cache():
    """Clear the mini-catalog cache (for testing)."""
    _catalog_cache.clear()

