"""
Mini-catalog loader for matching constraints.

The mini-catalog is a JSON file containing lightweight course metadata including
matching_required and matching_type fields. It's generated by the build script
and committed to the repo for static serving.

Locations searched:
1. ../web/public/course-index/{term}.json (when running from api/)
2. ./data/course_index_{term}.json (fallback for local development)
"""

import json
import os
from pathlib import Path
from typing import Any, Dict, Optional

# Cache mini-catalogs in memory
_catalog_cache: Dict[str, Dict[str, Any]] = {}


def _find_catalog_path(term: str) -> Optional[Path]:
    """Find the mini-catalog file for a term."""
    # Try multiple locations
    candidates = [
        # Primary: web/public/course-index (relative to api/)
        Path(__file__).parent.parent / "web" / "public" / "course-index" / f"{term}.json",
        # Fallback: api/data (old location)
        Path(__file__).parent / "data" / f"course_index_{term}.json",
    ]
    
    for path in candidates:
        if path.exists() and path.stat().st_size > 0:
            return path
    
    return None


def load_mini_catalog(term: str, force_refresh: bool = False) -> Dict[str, Any]:
    """
    Load the mini-catalog for a term.
    
    Returns a dict mapping course_code -> catalog entry.
    The entry contains: course_code, title, units, subject,
    and optionally: matching_required, matching_type, header_remarks
    
    Returns empty dict if catalog not found.
    """
    cache_key = term
    
    if not force_refresh and cache_key in _catalog_cache:
        return _catalog_cache[cache_key]
    
    catalog_path = _find_catalog_path(term)
    if not catalog_path:
        # Return empty dict - optimizer will use defaults
        _catalog_cache[cache_key] = {}
        return {}
    
    try:
        with open(catalog_path, "r") as f:
            entries = json.load(f)
        
        # Build lookup dict by course_code
        catalog = {}
        for entry in entries:
            code = entry.get("course_code")
            if code:
                catalog[code] = entry
        
        _catalog_cache[cache_key] = catalog
        return catalog
    
    except Exception as e:
        print(f"Warning: Failed to load mini-catalog for {term}: {e}")
        _catalog_cache[cache_key] = {}
        return {}


def get_matching_constraint(term: str, course_code: str) -> tuple[bool, Optional[str]]:
    """
    Get matching constraint for a specific course.
    
    Returns (matching_required, matching_type).
    Returns (False, None) if course not found in catalog.
    """
    catalog = load_mini_catalog(term)
    entry = catalog.get(course_code, {})
    
    return (
        entry.get("matching_required", False),
        entry.get("matching_type")
    )


def clear_cache():
    """Clear the mini-catalog cache (for testing)."""
    _catalog_cache.clear()

